project_name: go-sync-adapter-gen
before:
  hooks:
    - go mod tidy
builds:
  - main: cmd/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
universal_binaries:
  - replace: true
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
